### ISSUE TITLE
Is it impossible to configure two parallel primary models in a pipeline?

### ISSUE THREAD

**Issue by hadestyz** [prominenceai/deepstream-services-library#1164]
Hello:
      Assuming I have many video streams, some of which are bright scenes and some are dark scenes, I would like to input video streams from different scenes into different models. Obviously, the relationship between these two models is parallel, not primary and secondary. Should I establish two pipeline and configure two models in each pipeline to handle this matter? Just like an example:https://github.com/prominenceai/deepstream-services-library/blob/03e61d070e2cd15f6d6f6227d8dc71c1bd5190d7/examples/python/interpipe_multiple_pipelines_listening_to_single_sink.py#L281. 
      Is it impossible to configure two parallel primary models in a pipeline?

**Comment by rjhowell44** [comment]
Hey @hadestyz good timing!   I'm currently finishing up a new component called a [Remuxer](https://github.com/prominenceai/deepstream-services-library/blob/v0.29.alpha/docs/api-remuxer.md) designed specifically to support [Selective Parallel Inference](https://github.com/prominenceai/deepstream-services-library/blob/v0.29.alpha/docs/overview.md#selective-parallel-inference).  

This work is under the [v0.29.alpha](https://github.com/prominenceai/deepstream-services-library/tree/v0.29.alpha) dev branch.

It is far enough along for you to try it.   It would be great to get some feedback from others.  I'm currently working on the examples and I hope to release this next week some time.
