### ISSUE TITLE
Can I use v0.30alpha branch now？or When does the v0.30alpha branch merge into the master branch?

### ISSUE THREAD

**Issue by githubzhao735** [prominenceai/deepstream-services-library#1177]

**Comment by YoungjaeDev** [comment]
@githubzhao735 
As of today, 0.30.alpha seems to be no different from master

**Comment by rjhowell44** [comment]
@githubzhao735 I'm currently working on the gst_api branch for issues
* #1174
* #1176

which I hope to finish this week. Once finished, I will be pull into the v0.30.alpha branch... which will be usable, but unofficial.
I plan to release the v0.30.alph branch next week some time

**Comment by rjhowell44** [comment]
v0.30.alpha has been merged into master
