### ISSUE TITLE
Can not run Makefile with OpenCV or FFmpeg

### ISSUE THREAD

**Issue by subzeromot** [prominenceai/deepstream-services-library#1201]
I got error when build Makefile with OpenCV:

> /usr/bin/ld: warning: libavcodec.so.58, needed by /usr/lib/x86_64-linux-gnu/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: warning: libavutil.so.56, needed by /usr/lib/x86_64-linux-gnu/libopencv_videoio.so, not found (try using -rpath or -rpath-link)
> /usr/bin/ld: ./src/DslSinkBintr.o: undefined reference to symbol 'gst_video_overlay_expose'
> /usr/bin/ld: /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status

Also with FFmpeg:

> /usr/bin/ld: ./src/DslSinkBintr.o: undefined reference to symbol 'gst_video_overlay_expose'
> /usr/bin/ld: /lib/x86_64-linux-gnu/libgstvideo-1.0.so.0: error adding symbols: DSO missing from command line

My Makefile:
[Makefile.txt](https://github.com/prominenceai/deepstream-services-library/files/15204572/Makefile.txt)

**Comment by rjhowell44** [comment]
What version of DeepStream / ubuntu are you using?

**Comment by subzeromot** [comment]
I'm using docker image 'nvcr.io/nvidia/deepstream:6.2-devel', Ubuntu 20, opencv 4.9

**Comment by rjhowell44** [comment]
Sorry... but from the DSL README.md
_"The latest releases (v0.28.alpha and v0.29.alpha) were developed to support DeepSteam 6.3 and 6.4."_ 
I just don't have enough machines/devices/time to maintain more than two DeepStream releases at this time.

The DSL build instructions are for DeepStream 6.4. and ubuntu 22.  Is there anyway you can upgrade to ubuntu 22?

I'll be releasing DSL v0.30.alpha for DeepStream 7.0 (once released) hopefully next week.

**Comment by rjhowell44** [comment]
Would strongly suggest that you move to ubuntu 22 if you can

**Comment by subzeromot** [comment]
I'm testing on ubuntu 22, Deepstream 6.4, DSL v0.30.alpha.
I still found `/usr/include/gstreamer-1.0/gst/video/videooverlay.h` but when I build DSL with OpenCV or FFmpeg, it seems like they can not found it.

**Comment by subzeromot** [comment]
I backed to version v.0.29.alpha and it worked perfect
