### ISSUE TITLE
[Feature Request] Customization of filename generated by capture frame/object action

### ISSUE THREAD

**Issue by jlerasmus** [prominenceai/deepstream-services-library#351]
Currently the `CaptureOdeAction` generates a filename in the format `{outdir}/{triggerName}-{eventCount}.jpeg`

With the current convention:
- There is possibility to have the same filename generated if the application is restarted
- The eventCount starts at one, while Nvidia's smart-record files starts at zero
-- src-2-occurrence-trigger-1.jpeg
-- src-2-record-tap_00000_20200907-083819_29783.mkv

An improvement would be to allow the user to generate the filename via a callback.

PS! We should lobby for Nvidia to add file name customization for smart-record.  I have read in the forums that some users are renaming the files in the record-complete callback as a workaround.  Maybe DSL could provide this renaming functionality with the user able to customize the filename.

**Comment by rjhowell44** [comment]
this has been addressed with #444 
clients can change the file name or move the file in the notification callback, 
File name format has been updated to follow Nvidia's convention... without the usec

e.g. `bicycle-capture-action_00000_20210421-172618.jpeg`
