### ISSUE TITLE
Implement new ODE Persistence Trigger

### ISSUE THREAD

**Issue by rjhowell44** [prominenceai/deepstream-services-library#406]
Implement a new Trigger to detect ODE occurrence on unique object persistence... meaning, when a unique object as identified by Tracking ID persists beyond a specified period of time. 

An example use case would be to detect loitering. People can pass through the frame without triggering and event, as long as they do so within a specified period of time.

```C
/**
 * @brief Persistence trigger that checks for the persistence of Objects tracked for a. 
 * specified source and object class_id. Each object tracked or ">= minimum and <= maximum time 
 * will trigger an ODE occurrence.
 * @param[in] name unique name for the ODE Trigger
 * @param[in] source unique source name filter for the ODE Trigger, NULL = ANY_SOURCE
 * @param[in] class_id class id filter for this ODE Trigger
 * @param[in] limit limits the number of ODE occurrences, a value of 0 = NO limit
 * @param[in] minimum the minimum amount of time a unique object must remain detected 
 * before triggering an ODE occurrence - in units of seconds. 0 = no minimum
 * @param[in] maximum the maximum amount of time a unique object can remain detected 
 * before triggering an ODE occurrence - in units of seconds. 0 = no maximum
 * @return DSL_RESULT_SUCCESS on success, DSL_RESULT_ODE_TRIGGER_RESULT otherwise.
 */
DslReturnType dsl_ode_trigger_persistence_new(const wchar_t* name, 
    const wchar_t* source, uint class_id, uint limit, uint minimum, uint maximum);
```

**Comment by rjhowell44** [comment]
Done.

**Comment by zjd1988** [comment]
will support multi class id Persistence Trigger?

**Comment by rjhowell44** [comment]
@zjd1988 You can use `DSL_ODE_ANY_CLASS` to check for persistence on all classes

**Comment by zjd1988** [comment]
@[rjhowell44](https://github.com/rjhowell44)  thank you for your relpy.  I have a model output 7 class ,but I want to use 4 class persistence in the same polygon area

**Comment by rjhowell44** [comment]
@zjd1988, currently, you would need to create 4 persistence triggers. You can then add the same polygon area and actions to each of the 4 triggers.   That said, I've been considering extending the ODE Trigger object to support a list of Class id's.  I'm going to bring this up on our [Discord](https://discord.gg/MJvY9jjpAK) site to discuss with others.  Please join us if you're interested.

**Comment by zjd1988** [comment]
@rjhowell44 sounds greate！

**Comment by rjhowell44** [comment]
@zjd1988 ...  I plan to add the above (Class id list) in a future release, but I can say as to when I can get to it.  Lots of competing priorities.  Hopefully you're ok creating four separate triggers for the time being... and again, the Trigger can share the same polygon area and actions.

**Comment by zjd1988** [comment]
@rjhowell44 Ok, I will learn source codes to implement that by myself for the time being.

**Comment by rjhowell44** [comment]
@zjd1988 I just want to make sure that you understand that creating 4 separate triggers and adding each of them to the ODE handler will give you the same behavior as what you're looking for?  And that you'll be updating a tremendous amount of DSL code just to save a couple of lines of code in your application.
