### ISSUE TITLE
python breakpoint not work in osd_sink_pad_buffer_probe handler

### ISSUE THREAD

**Issue by 52doho** [prominenceai/deepstream-services-library#751]
Hi @rjhowell44 thank you for your great project, it makes deepstream api really simple!

I try all the python examples, only the osd_sink_pad_buffer_probe handler is not able to debug in vs code. I have install python and c++ extension for vs code.

I also google and search in [nvidia](https://forums.developer.nvidia.com/search?q=debug%20osd_sink_pad_buffer_probe) without getting any solution. How to debug [osd_sink_pad_buffer_probe](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/nvidia_osd_sink_pad_buffer_probe.py#L35) handler in python?

Many thanks.

**Comment by rjhowell44** [comment]
Hi @52doho , which script are you running when you are trying to debug the [osd_sink_pad_buffer_probe.py](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/nvidia_osd_sink_pad_buffer_probe.py#L35) 

I'm sure you're aware of this, but the file is a python module that is included/used by other example scripts. 
See [1uri_file_pgie_iou_tiler_osd_custom_pph_window.py](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/1uri_file_pgie_iou_tiler_osd_custom_pph_window.py) as one example. 

Are you saying that you are executing one of the scripts that includes the module, but when you set a break point in the module (in VS Code), the execution does not break?

If so... my apologies, but I'm not a VS Code user.  I use Codelite on my Jetson devices and I'm developing in C++.  Perhaps it's a debugger setting, or the way I've defined/included the module? I have not tried debugging this NVIDIA module myself. 

I'm going to bring this up with others on our [Discord](https://discord.gg/MJvY9jjpAK) server. There are a couple of VS Code/Python experts that might be able to help. You're more than welcome to come join us. 

Best regards,
Robert.

**Comment by 52doho** [comment]
Hi @rjhowell44, sorry for late response.

[1uri_file_pgie_iou_tiler_osd_custom_pph_window.py](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/1uri_file_pgie_iou_tiler_osd_custom_pph_window.py) calls osd_sink_pad_buffer_probe handler in [osd_sink_pad_buffer_probe.py](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/nvidia_osd_sink_pad_buffer_probe.py#L35) which is never break in debug.

Please refer these steps to reproduce.
1. breakpoint on pipeline, it works
<img width="1260" alt="python-debug-1-pipeline-breakpoint-ok" src="https://user-images.githubusercontent.com/174519/168050904-1752ea51-407d-4e9c-af0e-46851b6879dd.png">

2. breakpoint on state_change_listener, it works
<img width="1261" alt="python-debug-2-state_change_listener-ok" src="https://user-images.githubusercontent.com/174519/168052150-01d04400-4cdb-47ee-968e-43ff16747876.png">

3. breakpoint on osd_sink_pad_buffer_probe, it is not work, breakpoint never stop
![python-debug-3-osd_sink_pad_buffer_probe-never-called](https://user-images.githubusercontent.com/174519/168051733-3fbde141-5637-4dec-853c-de2ab5758819.png)

By the way, breakpoint on osd_sink_pad_buffer_probe can stop in c++ debug.
<img width="1270" alt="cpp-debug-4-osd_sink_pad_buffer_probe-ok" src="https://user-images.githubusercontent.com/174519/168054004-b0f5562b-0646-4a79-a315-370cc0bb7660.png">

**Comment by rjhowell44** [comment]
@52doho I've brought your question up on our Discord Server... I'll let you know if I get a response. Unfortunately, I don't have the VSCode experience to be able to help.

**Comment by rjhowell44** [comment]
@52doho In the meantime, you can always copy the callback function into the script you're running.

**Comment by 52doho** [comment]
Great! Build apps on python DSL api is faster than cpp api. It will help the whole community. Thanks for your great work!

**Comment by niderhoff** [comment]
Breakpoints in python probes never work in VS Code in my experience.
What did work was setting a breakpoint using pdb.

**Comment by 52doho** [comment]
@niderhoff You are right. after add breakpoint() to osd_sink_pad_buffer_probe handler, vscode python debugger can pause now. 

Thank you @niderhoff
<img width="1268" alt="python-debug-3-osd_sink_pad_buffer_probe-ok" src="https://user-images.githubusercontent.com/174519/168777406-39b2f6cd-b582-4478-bbb3-82b5c54470ae.png">

**Comment by rjhowell44** [comment]
@niderhoff thank you so much for helping out here. Very much appreciated.  I'm going to add a note and link to the VSCode docs page.

... and please consider joining us on our [Discord](https://discord.gg/MJvY9jjpAK) server were we're discussing new features and DSL's roadmap. Insights and new ideas are always welcome.
