### ISSUE TITLE
jetson nano window bottleneck, delay when running 1file_ptis_dcf_osd_window.py file

### ISSUE THREAD

**Issue by youngjae-avikus** [prominenceai/deepstream-services-library#760]
Hello

When run `1file_ptis_dcf_osd_window.py,` it runs well until window load -> engine load
During the actual interference, the video is delayed and comes out
I felt that the first part of the video was filled with the queue, and I could see that the video was being processed at once, and the video was moving fast at first part
Is this because of jetson nano's performance delaying the osd?
Even if modify the dcf config to `max_perf`, I can see a little osd delay

- my jetson stats
![image](https://user-images.githubusercontent.com/99321359/168533011-f10a6fb9-245a-4d25-83b4-5429a323cd95.png)

**Comment by rjhowell44** [comment]
@youngjae-avikus I will need to look into this... I see the same issue as you do.  I will need to build and test with the `apps/sample_apps/deepstream-test2`  (uses the DCF tracker) to compare.
