### ISSUE TITLE
question about dsl_ode_occurrence_info

### ISSUE THREAD

**Issue by youngjae-avikus** [prominenceai/deepstream-services-library#800]
I am currently using monitor_action, and I am using trigger and action as below

```python
retval = dsl_ode_trigger_occurrence_new('every-occurrence-trigger', 
     source = DSL_ODE_ANY_SOURCE, 
     class_id = DSL_ODE_ANY_CLASS, 
     limit = DSL_ODE_TRIGGER_LIMIT_NONE)
if retval != DSL_RETURN_SUCCESS:
     return -1

retval = dsl_ode_action_monitor_new('every-occurrence-monitor',
        client_monitor = ode_occurrence_monitor,
        client_data = None)
    if retval != DSL_RETURN_SUCCESS:
        return -1
```

https://github.com/prominenceai/deepstream-services-library/blob/v0.25.alpha/docs/api-ode-action.md#dsl_ode_occurrence_info

Now, the situation I'm implementing is that I'm putting the detected objects in every frame on a list and sending them to zmq at a time. Even if there is no object in the frame, I should update it by delivering an empty list for each frame. However, the problem is that the current trigger, action, becomes an action whenever an object is found, so it is not an object update for all frames

In the meantime, I have a question about the `is_object_occurrence` variable. Of course, it comes into the action, so I think it will be true unconditionally, so how can I use it for that variable and can I get some advice on the situation above???

Thank you!

**Comment by youngjae-avikus** [comment]
@rjhowell44 

Think of it simply and don't be subordinate to trigger & action, but can implement with a pph of fakesink PAD_SINK?

**Comment by rjhowell44** [comment]
@youngjae-avikus you can do you're own processing of the batch_meta with a custom pph ... the triggers just make it easy to setup minimum criteria for occurrence... meaning, filtering of objects based on minimum criteria, whether that is source-id, confidence level, min/max dimensions, time-in frame, location within the frame, movement within the frame etc.  If you're just simply reporting all objects, then the custom pph might be the simplest approach.

**Comment by rjhowell44** [comment]
@youngjae-avikus I wanted to first try and see if I could add an object to each frame - same location/color for each frame with the following
```C
uint custom_client_handler_cb(void* buffer, void* client_data)
{
    GstBuffer* pGstBuffer = (GstBuffer*)buffer;

    NvDsBatchMeta* pBatchMeta = gst_buffer_get_nvds_batch_meta(pGstBuffer);
    
    for (NvDsMetaList* pFrameMetaList = pBatchMeta->frame_meta_list; 
        pFrameMetaList != NULL; pFrameMetaList = pFrameMetaList->next)
    {
        NvDsFrameMeta* pFrameMeta = (NvDsFrameMeta*)(pFrameMetaList->data);
        
        NvDsObjectMeta* pObjectMeta = nvds_acquire_obj_meta_from_pool(pBatchMeta);
        
        pObjectMeta->rect_params.left = 500;
        pObjectMeta->rect_params.top = 100;
        pObjectMeta->rect_params.width = 100;
        pObjectMeta->rect_params.height = 100;
        pObjectMeta->rect_params.border_width = 5;
        pObjectMeta->rect_params.border_color.red = 0.0;
        pObjectMeta->rect_params.border_color.blue = 1.0;
        pObjectMeta->rect_params.border_color.green = 0.0;
        pObjectMeta->rect_params.border_color.alpha = 1.0;
        
        nvds_add_obj_meta_to_frame(pFrameMeta, pObjectMeta, NULL);
        
    }
    return DSL_PAD_PROBE_OK;
}
```

And this works... so starting to look at your specific example now.

**Comment by rjhowell44** [comment]
@youngjae-avikus looking at the object meta data that you're adding, 
```
rect_params.left = 406.0
rect_params.top = 481.0
rect_params.width = 54.0
rect_params.height = 153.0
rect_params.border_width = 0
rect_params.border_color.red = 0.0
rect_params.border_color.green = 0.0
rect_params.border_color.blue = 0.0
rect_params.border_color.alpha = 0.0
```
`border_width` must be greater than 1 and colors and alpha level are not set.  OSD will not display anything with these values.

**Comment by rjhowell44** [comment]
@youngjae-avikus I just realized that you are formatting the bounding box width and color with an ODE action, so disregard what I said above.

**Comment by rjhowell44** [comment]
@youngjae-avikus I found that if I just fix the alpha level and border values in the callback the OSD displays the bounding-boxes.


![Screenshot from 2022-07-01 19-45-34](https://user-images.githubusercontent.com/7819483/176983950-4d430fab-b695-444a-adac-2641d87af254.png)

I also added a Print action to the every-occurrence-trigger and see the following
```
Trigger Name        : every-occurrence-trigger
  Unique ODE Id     : 0
  NTP Timestamp     : 2022-07-01 19:45:40.147729
  Source Data       : ------------------------
    Inference       : Yes
    Source Id       : 0
    Batch Id        : 0
    Pad Index       : 0
    Frame           : 252
    Width           : 1920
    Heigh           : 1080
  Object Data       : ------------------------
  Criteria          : ------------------------
    Class Id        : 2147483647
    Min Infer Conf  : 0
    Min Track Conf  : 0
    Min Frame Count : 1 out of 1
    Min Width       : 0
    Min Height      : 0
    Max Width       : 0
    Max Height      : 0
    Inference       : No
```
I see one per frame and the object data is null ... which leads me to believe that the new object-meta is added as `user-meta` which the ODE-PPH is not looking for. 

I'll be able to confirm this in the morning

**Comment by rjhowell44** [comment]
@youngjae-avikus I found the problem.... two simple changes required

First, you may have just been trying different values here, but I changed
```python
                out_meta_data.class_id = 1
```
to 
```python
                out_meta_data.class_id = pred[-1]['class_id']
```

Second, your every-occurrence trigger was created with `dsl_ode_trigger_always_new` which is a frame level trigger to trigger on every frame once always.... typically used to overlay display data on every frame... see [dsl_ode_trigger_always_new](https://github.com/prominenceai/deepstream-services-library/blob/master/docs/api-ode-trigger.md#dsl_ode_trigger_always_new).  I changed 
```python
    retval = dsl_ode_trigger_occurrence_new('every-occurrence-trigger', DSL_ODE_ANY_SOURCE, 0)
```
to a [dsl_ode_trigger_occurrence_new](https://github.com/prominenceai/deepstream-services-library/blob/master/docs/api-ode-trigger.md#dsl_ode_trigger_occurrence_new) to trigger on the occurrence of every object (all classes)
```python
    retval = dsl_ode_trigger_occurrence_new('every-occurrence-trigger', 
        DSL_ODE_ANY_SOURCE, DSL_ODE_ANY_CLASS, DSL_ODE_TRIGGER_LIMIT_NONE)
```
Working better after these changes.

**Comment by youngjae-avikus** [comment]
> @youngjae-avikus I found the problem.... two simple changes required
> 
> First, you may have just been trying different values here, but I changed
> 
> ```python
>                 out_meta_data.class_id = 1
> ```
> 
> to
> 
> ```python
>                 out_meta_data.class_id = pred[-1]['class_id']
> ```
> 
> Second, your every-occurrence trigger was created with `dsl_ode_trigger_always_new` which is a frame level trigger to trigger on every frame once always.... typically used to overlay display data on every frame... see [dsl_ode_trigger_always_new](https://github.com/prominenceai/deepstream-services-library/blob/master/docs/api-ode-trigger.md#dsl_ode_trigger_always_new). I changed
> 
> ```python
>     retval = dsl_ode_trigger_occurrence_new('every-occurrence-trigger', DSL_ODE_ANY_SOURCE, 0)
> ```
> 
> to a [dsl_ode_trigger_occurrence_new](https://github.com/prominenceai/deepstream-services-library/blob/master/docs/api-ode-trigger.md#dsl_ode_trigger_occurrence_new) to trigger on the occurrence of every object (all classes)
> 
> ```python
>     retval = dsl_ode_trigger_occurrence_new('every-occurrence-trigger', 
>         DSL_ODE_ANY_SOURCE, DSL_ODE_ANY_CLASS, DSL_ODE_TRIGGER_LIMIT_NONE)
> ```
> 
> Working better after these changes.

I have a question about the second proposal, is it certain that `dsl_ode_trigger_always_new` was the cause? Is not `dsl_ode_trigger_always_new` a broad concept that includes `dsl_ode_trigger_occurrence_new`?

**Comment by youngjae-avikus** [comment]
My question is that I think there will be no problem using both `dsl_ode_trigger_occurrence_new` and `dsl_ode_trigger_always_new`, but of course, I think `dsl_ode_trigger_always_new` is inefficient in terms of resource usage, so is there a problem in working?

**Comment by rjhowell44** [comment]
@youngjae-avikus as I'm sure you're aware, coming up with simple, intuitive names can be harder than writing the actual code at times.  `dsl_ode_trigger_always_new` is a special class of trigger, and is the only trigger that does NOT evaluate object data.  Perhaps there is a better name.  `dsl_ode_trigger_occurrence_new` only becomes a type of "always trigger" when you set the source-filter to `DSL_ODE_ANY_SOURCE`, the class-filter to `DSL_ODE_ANY_CLASS`, and the limit-filter to `DSL_ODE_TRIGGER_LIMIT_NONE` ... otherwise it is anything but an always trigger, especially once you set other critter on the Trigger as well.  I hope this helps to clarify.

**Comment by youngjae-avikus** [comment]
> @youngjae-avikus as I'm sure you're aware, coming up with simple, intuitive names can be harder than writing the actual code at times. `dsl_ode_trigger_always_new` is a special class of trigger, and is the only trigger that does NOT evaluate object data. Perhaps there is a better name. `dsl_ode_trigger_occurrence_new` only becomes a type of "always trigger" when you set the source-filter to `DSL_ODE_ANY_SOURCE`, the class-filter to `DSL_ODE_ANY_CLASS`, and the limit-filter to `DSL_ODE_TRIGGER_LIMIT_NONE` ... otherwise it is anything but an always trigger, especially once you set other critter on the Trigger as well. I hope this helps to clarify.

`dsl_ode_trigger_always_new` does not approach the action on object data?

**Comment by rjhowell44** [comment]
@youngjae-avikus .. This frame level trigger only operates on `frame-meta`.  If you add a `print` or `log` action to the trigger, it would print out or log the frame metadata for each frame.  If you ad a `capture-frame` action then it would capture each frame to a jpeg file.  Adding other types of actions, such as the `format label` action results in a nop.  There are other types of frame-level triggers that do look at object data.  A `summation` trigger for example.  It will trigger once per frame with the summation of all objects in the frame.  Adding a `format label` action to this trigger will also result in a nop.
