### ISSUE TITLE
undefined function cv::Mat::Mat() , Error while building 

### ISSUE THREAD

**Issue by bharathraja** [prominenceai/deepstream-services-library#805]
I get the following error while building the library. I have installed all per-requisites. I have opencv 4.5.5 and trying to build it in Jetson Xavier platform. 

> `DslOdeAction.cpp:(.text+0x2fc0): undefined reference to `cv::Mat::Mat(cv::Size_<int>, int)'
> ./test/unit/DslOdeActionUnitTest.o: In function `____C_A_T_C_H____T_E_S_T____48()':
> DslOdeActionUnitTest.cpp:(.text+0x5644): undefined reference to `cv::Mat::Mat(cv::Size_<int>, int)'
> collect2: error: ld returned 1 exit status
> Makefile:169: recipe for target 'dsl-test-app.exe' failed
> make: *** [dsl-test-app.exe] Error 1
> `

The package config for opencv4 gives the following output:

> '-I/usr/local/include/opencv4 -L/usr/local/lib -lopencv_gapi -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_barcode -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cudabgsegm -lopencv_cudafeatures2d -lopencv_cudaobjdetect -lopencv_cudastereo -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_cudacodec -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_videostab -lopencv_cudaoptflow -lopencv_optflow -lopencv_cudalegacy -lopencv_videoio -lopencv_cudawarping -lopencv_wechat_qrcode -lopencv_xfeatures2d -lopencv_shape -lopencv_ml -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_cudaimgproc -lopencv_cudafilters -lopencv_imgproc -lopencv_cudaarithm -lopencv_core -lopencv_cudev
> '

**Comment by rbgreenway** [comment]
I haven't looked at this in detail, but my instincts tell me it's one of two things:
1 - you have a signature mismatch for the Mat constructor.  I don't *think* this is the problem because I think the (cv::Size, int) signature is right.
2 - the opencv_core library is not getting linked.  I see that it's in your list, but that doesn't necessarily mean it's getting linked.
In a terminal, try running ldd on libopencv_core.so to see it's dependencies and make sure you have all of them.
  Here's the command, in case you need it (and I'm guessing where your opencv libs are):
      `$ ldd /usr/lib/x86_64-linux-gnu/libopencv_core.so`

**Comment by bharathraja** [comment]
> @bharathraja do you have a particular need to build/use `opencv 4.5.5`?
> 
> In order to simplify the installation we've been building DSL using the `python3-opencv` distribution, which on the Jetson platform (stuck on Unbuntu 18) installs `opencv 3.2.0` - which is really old.
> 
> I had a quick discussion with one of our contributors on our [Discord](https://discord.gg/MJvY9jjpAK) site -- please join if you're interested -- who is building/using `opencv 4.2` with DSL. Is there a chance you could try with this version.
> 
> Looking ahead, DSL has very minimal dependencies on opencv and I may be able to make DSL's use version compatible. I will try and look into this soon.
> 
> Regards, Robert.

@rjhowell44 , I was using new version of opencv 4.5.5 for another project. So, tried to install with it. I will try with the setup you suggested. Thanks for quick response.

@rbgreenway , i tried ldd for the opencv-core library. it has all the dependencies. The version mismatch or change in opencv mat format might be the reason i think. I am looking into it. Thanks a lot.

**Comment by bharathraja** [comment]
its working, when i added extra library flags "-L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui" to makefile. i will update in git and close the issue. i think it is due to some linking error.

> $(APP): $(OBJS) Makefile	
> 	$(CXX) -L/usr/local/lib -lopencv_core -lopencv_imgproc -lopencv_highgui -o $(APP) $(OBJS) $(CFLAGS) $(LIBS)

**Comment by rjhowell44** [comment]
@bharathraja I want to keep this open until updates can be made and released.  I'll close it then. Thanks.

**Comment by rjhowell44** [comment]
Makefile updates merged into v0.25.alpha
