### ISSUE TITLE
Can Gst-interpipe be added to Deepstream-services-library ?

### ISSUE THREAD

**Issue by bharathraja** [prominenceai/deepstream-services-library#808]
[Gst-interpipe](https://github.com/RidgeRun/gst-interpipe) is used to dynamically handle multiple pipeline inter-connections. Can this be added to the DSL. 

Is there any documentation or tutorial on how to add a custom plugin ?

**Comment by rjhowell44** [comment]
@bharathraja not currently, but the interpipe plugins look very interesting! I will take some time to review this weekend and see what it would take to add to DSL.

**Comment by rjhowell44** [comment]
This discussion has been continuing on [Discord](https://discord.gg/MJvY9jjpAK) ... support will most likely be included in the v0.26.alpha milestone.

**Comment by rjhowell44** [comment]
This issue has be superseded by **Implement new Inter-Pipe Sink and Source components** #828
