### ISSUE TITLE
when we stop the pipeline and then start pipeline at that time dsl reload model in the inference engine?

### ISSUE THREAD

**Issue by Ritesh1991** [prominenceai/deepstream-services-library#837]
Is model loaded in memory on the creation of pipeline, I want to run my pipeline on certain external trigger. when it tirgger pipeline start for next trigger pipeline inference stop, But dont want to reload model in memory every time when it starts.

**Comment by rjhowell44** [comment]
@Ritesh1991 the NVIDIA inference plugin will cache the model once loaded...  i.e. model should only load once.
