### ISSUE TITLE
Use DSL inside actual DS python sample code

### ISSUE THREAD

**Issue by ayanasser** [prominenceai/deepstream-services-library#864]
Hello, 
I'm very happy that I passed through this amazing repo, thank you for your contributions.
I am already working with deepstream python samples, and have my application, but sometimes I need to use features as rtsp reconnecting or msgbroker, my question is do you know if I could build the pipeline with DS samples but use one or more features from your code ?

Or this is no applicable and I should build the pipeline itself from the beginning with DSL ?

**Comment by rjhowell44** [comment]
@ayanasser it could be challenging to mix, in most cases, as DSL aims to the abstract the use of GStreamer. That said, anywork you've done to process the batch metadata in DS could be reused in a DSL custom Pad Probe Handler. 

I'm hopeful that you will find DSL much easier to work with than DS and GStreamer and that converting to DSL should be somewhat straight forward.

**Comment by ayanasser** [comment]
Thank you ^^
