### ISSUE TITLE
[Requirement] source_input in binary (bytes) form

### ISSUE THREAD

**Issue by youngjae-avikus** [prominenceai/deepstream-services-library#899]
Hello
Assuming that the image itself is received from the same DB(Elastic Redis, etc ..) as amazon s3, it is often transferred to byte form.
I use it converted as an array as below, and I would like to request you to implement the source_new API for this.

```python
from io import BytesIO

...

def infer_img_bytes(self, img_bytes):
        img_array = np.array(Image.open(BytesIO(img_bytes)).convert('RGB'))
        return self.infer_img_array(img_array)
```

**Comment by rjhowell44** [comment]
@youngjae-avikus I believe this can be done using the new App Source... initial implementation has been merged into v0.26.alpha.  See docs here... [dsl_source_app_new](https://github.com/prominenceai/deepstream-services-library/blob/v0.26.alpha/docs/api-source.md#dsl_source_app_new)

There is a lot you can do with App Source, so we may need to experiment a little as to how to handle your use case. I've implemented just one the example [here](https://github.com/prominenceai/deepstream-services-library/blob/v0.26.alpha/examples/cpp/raw_i420_app_src_ptis_tracker_osd_window.cpp) that feeds raw buffers using file data. 

There are some examples of using numpy with the App Source plugin if you search around... one example [here](https://gist.github.com/marekyggdrasil/ede6961155ca6670dbc53eaac818dc6d)

Please review and see if you think App Source will meet your needs.
