### ISSUE TITLE
Questions about availability of redis msgbroker, ODE message action, and message sink

### ISSUE THREAD

**Issue by youngjae-avikus** [prominenceai/deepstream-services-library#960]
1. [Confirmation] If I put the redis lib in the nvmsgbroker api, it seems to work without problems. Is it right?
2. [Request] Is it possible to implement a C++ Example that sends a message in the form of a dictionary (payload?) whenever an inference result occurs? If look at the python example code now, there is no such content. Is there a way to pass inference + tracker information using `dsl_sink_message_new`?
3. Looking at the example description, [message_broker_azure_device_client.py](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/message_broker_azure_device_client.py) a simple example that sends a "hello world" string to an Azure Hub Instance. How to send more complex payloads in Python is still to be determined. C/C++ is more straight forward.
What does it mean exactly?

Thank you!

**Comment by rjhowell44** [comment]
1. [Confirmation] If I put the redis lib in the nvmsgbroker api, it seems to work without problems. Is it right?

*According to NVIDIA, this is a key feature of the broker, similar to the MOT, so yes. That said, I have not tried all the libs myself.  Here's a link to many of the message broker related discussions on NVIDIA's forum https://forums.developer.nvidia.com/search?q=message%20broker*

2. [Request] Is it possible to implement a C++ Example that sends a message in the form of a dictionary (payload?) whenever an inference result occurs? If look at the python example code now, there is no such content. Is there a way to pass inference + tracker information using dsl_sink_message_new?
 
*First, take a look at [ode_instance_trigger_message_server.py](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/ode_instance_trigger_message_server.py).  The example uses a New Instance Trigger (triggers on new tracking id) with an [dsl_ode_action_message_meta_add_new](https://github.com/prominenceai/deepstream-services-library/blob/master/docs/api-ode-action.md#dsl_ode_action_message_meta_add_new) action which generates a [NvDsEventMsgMeta](https://docs.nvidia.com/metropolis/deepstream/4.0/dev-guide/DeepStream_Development_Guide/baggage/structNvDsEventMsgMeta.html) structure, populates it, and adds it to the frame metadata.  The [Message-Sink](https://github.com/prominenceai/deepstream-services-library/blob/master/docs/api-sink.md#dsl_sink_message_new) added downstream will convert and send the structure to the server.  Take a look at the code [here](https://github.com/prominenceai/deepstream-services-library/blob/cdf65f6ec961e535eb1f6d3b7c6bdbe505e72927/src/DslOdeAction.cpp#L1811) to see which fields I'm populating. Let me know if I'm missing anything you need.  There is a way to add custom data as well. Not currently supported.* 

3. Looking at the example description, [message_broker_azure_device_client.py](https://github.com/prominenceai/deepstream-services-library/blob/master/examples/python/message_broker_azure_device_client.py) a simple example that sends a "hello world" string to an Azure Hub Instance. How to send more complex payloads in Python is still to be determined. C/C++ is more straight forward.
What does it mean exactly?

*re: **How to send more complex payloads in Python is still to be determined. C/C++ is more straight forward.**. Not very helpful, I agree.  This statement has more to do with my own experience.  For me, it's easier to see how you could use a padded C structure and serialize/de-serialize the structure into/out-of a byte buffer.  I have no experience doing anything like this in Python.* 

*Also, unfortunately, I have had not had the time to look into working on the client side and how to use the data sent from the device.  I would suggest looking for examples from the NVIDIA search link I provided above. Please share your findings and experience if you can*
