### ISSUE TITLE
Why does my program will be blocked when I use dsl_pipeline_component_remove to remove one source?

### ISSUE THREAD

**Issue by popcornGit** [prominenceai/deepstream-services-library#984]

**Comment by rjhowell44** [comment]
@popcornGit my apologies for the late response. Can you please provide me with more information.
* Jetson or dGPU?
* Deepstream version? 
* How many sources are you using?
* When the program blocks, is it on the first call to component-remove, or is it when removing the last source?
* Is the main-loop running when you remove the source?

Please provide a full log-file of the scenario. Please enable logging with
```
export GST_DEBUG=1,DSL:4
```
and direct the logs to a file with the following
```
export GST_DEBUG_FILE=./dsl.log
```
Thanks
